# CC is for the compilier I am using and CXXFLAGS is for the defintion of what else I want with the compile

CC = g++
CXXFLAGS = -Wall -Wextra -pedantic

strike.o: strike.cpp strike.h action.h
	 $(CC) $(CFLAGS) -c strike.cpp strike.h action.h